### ISSUE TITLE
Are closures supported?

### ISSUE THREAD

**Issue by hiqsol** [Riimu/Kit-PHPEncoder#7]
Thanks!

**Comment by Riimu** [comment]
No.. that's not really possible. I mean, how would that even work? Closures take advantage of enclosing surrounding scope so what would be benefit of encoding them?

I suppose in a very limited use case you could possibly lift the source code from the original file for closure (assuming it has definition in source code) using reflection, but that's quite complex and I'm not sure how useful that would be (you'd lose `use` variables and `$this` scope essentially).

Do you have some specific use case in mind? PHP doesn't really provide any internal way to encode closures to PHP code and it's not possible to get the PHP code for closures using PHP's standard library.

**Comment by hiqsol** [comment]
> No.. that's not really possible

Yes. But it is partially possible as you said by lifting source code from original file.
I know the limitations of this approach but it is ok for many practical cases.

> Do you have some specific use case in mind?

Yes. I develop https://github.com/hiqdev/composer-config-plugin
It assembles configurations distributed with composer packages.
Configuration can include closures.
You can look how I implemented simple closures support: https://github.com/hiqdev/composer-config-plugin/blob/master/src/Helper.php#L71

At the moment I use `var_export()` and you know it's deficiencies.
That's why I was interested if you consider adding support for closures for I could throw away all my array exporting stuff and use your lib.

Also better support for closures could be implemented with use of something like https://github.com/jeremeamia/super_closure or other libraries based on `nikic/php-parser`.
The chosen library could be suggested and not required by your lib and then you could check if needed class is available and then use it or use simple implementation.

**Comment by Riimu** [comment]
If you just want to use a wrapper for SuperClosure, for example, that's already pretty simple with the current library. Here is how you could implement it, for example:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$closure = function ($a, $b) {
    return $a + $b;
};

$closureEncoder = new class implements \Riimu\Kit\PHPEncoder\Encoder\Encoder {
    public function getDefaultOptions()
    {
        return [];
    }

    public function supports($value)
    {
        return $value instanceof Closure;
    }

    public function encode($value, $depth, array $options, callable $encode)
    {
        $serializer = new \SuperClosure\Serializer();

        return sprintf('unserialize(%s)', $encode($serializer->serialize($value)));
    }
};

$foo = [
    'func' => $closure,
];

$encoder = new \Riimu\Kit\PHPEncoder\PHPEncoder();
$encoder->addEncoder($closureEncoder, true);

$result = eval('return ' . $encoder->encode($foo) . ';');

echo $result['func'](2, 3);
```

I'm not very keen on adding support for SuperClosure by default, however.

The issues is that it deals with serialization rather than code export. While, yes, the current object encoder does support using the 'serialize' format for objects, I don't really like the idea of getting into habit of building support for different kind of language features via serialization.

Adding a "native" support for closures does seem somewhat interesting challenge, however. I may look into that in some time frame. It will, however, have a bit more limitations compared to SuperClosure as you can't deal with the context in the same as you can when taking advantage of serialization.

**Comment by hiqsol** [comment]
That's cool you have support for custom encoders.
That seems quite enough.
Thank you for your time and comprehensive example!
